#!/bin/bash
# Configure backend URL for Visual-NN frontend

echo "🔧 Visual-NN Backend Configuration"
echo "=================================="

# Default values
DEFAULT_PORT="5001"
DEFAULT_HOST="localhost"

# Get user input or use environment variables
BACKEND_HOST=${BACKEND_HOST:-$DEFAULT_HOST}
BACKEND_PORT=${BACKEND_PORT:-$DEFAULT_PORT}

echo "Current configuration:"
echo "  Host: $BACKEND_HOST"
echo "  Port: $BACKEND_PORT"
echo "  Full URL: http://$BACKEND_HOST:$BACKEND_PORT"

# Create config.js
cat > config.js << EOF
/**
 * Frontend Configuration for Visual-NN
 * Generated by set_backend_url.sh
 */

// Backend configuration
window.BACKEND_PORT = '$BACKEND_PORT';
window.BACKEND_URL = 'http://$BACKEND_HOST:$BACKEND_PORT';

// Configuration info
console.log('🔧 Backend configured for: http://$BACKEND_HOST:$BACKEND_PORT');
EOF

echo "✅ Configuration updated in config.js"
echo ""
echo "🚀 Usage examples:"
echo "  # Local development:"
echo "  ./set_backend_url.sh"
echo ""
echo "  # Custom port:"
echo "  BACKEND_PORT=8080 ./set_backend_url.sh"
echo ""
echo "  # EC2 deployment:"
echo "  BACKEND_HOST=your-ec2-ip BACKEND_PORT=5001 ./set_backend_url.sh"
echo ""
echo "  # Production:"
echo "  BACKEND_HOST=api.yourdomain.com BACKEND_PORT=443 ./set_backend_url.sh"
